apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      containers:
        - name: argocd-repo-server
          command:
            - /var/run/argocd/argocd-cmp-server
          volumeMounts:
            - name: cmp-plugin
              mountPath: /home/argocd/cmp-server/plugins
            - name: sops-age
              mountPath: /etc/sops/age
              readOnly: true
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /etc/sops/age/age.agekey
      volumes:
        - name: cmp-plugin
          configMap:
            name: argocd-cmp-sops
        - name: sops-age
          secret:
            secretName: sops-age
