# git_ops-K8-config/base/booking-app/postgresql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  # Base64 kódované PLACEHOLDERY.
  postgres-user: cGxhY2Vob2xkZXI= 
  postgres-password: cGxhY2Vob2xkZXI=
