# git_ops-K8-config/base/insurance-app/mail-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
type: Opaque
data:
  # Base64 kódované hodnoty (tu len placeholder)
  smtp-host: cGxhY2Vob2xkZXI= # placeholder
  smtp-password: cGxhY2Vob2xkZXI= # placeholder
